### ISSUE TITLE
Have a way to manage XML Attribute in YAML pom

### ISSUE THREAD

**Issue by ChtiDkois** [takari/polyglot-maven#118]
Some plugins have configuration with no other way than an XML Attribute, but there is no equivalent in YAML for this.

As example, this is a maven-antrun-plugin configuration :

```
            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-surefire-workdir</id>
                        <phase>generate-test-sources</phase>
                        <configuration>
                            <!-- do not generate if tests are skipped -->
                            <skip>${maven.test.skip}</skip>
                            <target>
                                <mkdir dir="${basedir}/target/surefire-workdir" />
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

Here, the mkdir element contains a "dir" attribute that cannot be transform into element.
I haven't found a way in YAML to describe this behavior.

```
  - groupId: org.apache.maven.plugins
    artifactId: maven-antrun-plugin
    executions:
    - id: generate-surefire-workdir
      phase: generate-test-sources
      # Do not generate if tests are skipped
      configuration:
        skip: ${maven.test.skip}
        target:
          mkdir: {dir: '${basedir}/target/surefire-workdir'}
      goals: [run]
```

I tried several way to put the "dir" value, no success.

Maybe we could have something like
```

        target:
          mkdir: 
            attr : {dir: '${basedir}/target/surefire-workdir'}
```
to specify we want it as a XML attribute ?

**Comment by callmetango** [comment]
My 0,02€/$/...: I had a look at adding attributes when working on issue #62. When researching I found the [YAML2 attributes draft](https://github.com/yaml/YAML2/wiki/attributes) which didn't convince me for its syntactical deviation from the rest of the language. My second look was at the [Node Properties section of the YAML 1.2 language spec](http://www.yaml.org/spec/1.2/spec.html#id2783797), especially the [Node Anchors](http://www.yaml.org/spec/1.2/spec.html#id2785586). Since node properties prefix the node they seem not applicable when adding attributes.

Thinking of attributes I think of special key-value mappings added to a node. So what I came up with was the following **Variant 1** introducing a new global type `!!attr`:
~~~ yaml
# Explicitly typed attributes.
plainTagWithAttributes: 42
  !!attr id: the-answer
  !!attr name: the answer to life, the universe and everything
# Flow style
plainTagWithAttributes: !!attr [ id: the-answer, name: "... to life ..." ] 42
~~~

**Variant 2** is using the yet to introduce global type `!!attr` and the [`!!value`](http://yaml.org/type/value.html) type for specifying default values for mappings as well which leads obviously to a more verbose result:
~~~ yaml
# Explicitly typed attributes
plainTagWithAttributes:
  = : 42
  !!attr id: the-answer
  !!attr name: the answer to life, the universe and everything
# Flow style
plainTagWithAttributes: { = : 42 !!attr [ id: the-answer, name: "... to life ..." ] }
~~~

Used with a [`!!map`](http://yaml.org/type/map.html) this could give results even acceptable by Maven pom.xml veterans: 
~~~ yaml
# Explicitly typed attributes.
transformers:
  - !!attr implementation: "FooTransformer"
    mainClass: Xxxx
  - !!attr implementation: 'BarTransformer'
    resource: .groovy
# Flow style
transformers: [ {!!attr implementation: "FooTransformer",  mainClass: Xxxx}, {!!attr implementation: "BarTransformer"} resource: .groovy}} ]
~~~

Of course all of the above require changes either to the composer used by `polyglot-yaml` or worse to the SnakeYAML parser. A straight forward attempt to parse the above examples failed me since these are obviously not YAML conformant. Which doesn't mean we should give up here. ;-)

A possibility was to use the [Low Level API](https://bitbucket.org/asomov/snakeyaml/wiki/Documentation#markdown-header-low-level-api) of SnakeYAML to extend the parser and/or composer. What do you think?

**Comment by Tzrlk** [comment]
As much as I love the terseness of Variant 1, using the existing functionality in SnakeYAML is probably way easier and better in the long run. Since there's no `!!attr` type ([according to the docs](http://yaml.org/type/index.html)), treating any `!!map` that contains a `!!value` (`=:`) as all other entries being attributes would solve the issue. Sadly, this does mean that if you have a `!!map` with attributes, you'd need to declare the `!!value` as the content map.

```yaml
plainTagWithAttributes:
  id: the-answer
  name: the answer to life, the universe and everything
  =: 42

mapWithAttributes:
  cool: false
  clear: maybe
  =:
    color: blue
    sadness: palpable
```

If they're going to implement the `!!attr` type some time soon, then Variant 2 becomes the obvious choice.
