### ISSUE TITLE
[polyglot-yaml] Add map support for dependency parsing

### ISSUE THREAD

**Issue by Tzrlk** [takari/polyglot-maven#148]
One thing I've wanted for a while to keep my dependencies clearly fenced was a map-based approach:

```yaml
dependencies:

  compile:
    - &kotlin { groupId: org.jetbrains.kotlin, artifactId: kotlin-stdlib-jre8, version: 1.1.51 }
    - &slf4j  { groupId: org.slf4j,            artifactId: slf4j-api,          version: 1.7.22 }

  test:
    - { groupId: junit, artifactId: junit, version: "${version.junit}" }
    - { <<: *kotlin, artifactId: kotlin-test }
    - { <<: *kotlin, artifactId: kotlin-reflect }
    - { <<: *slf4j,  artifactId: slf4j-log4j12 }

```

This is very much a nice-to-have, but it makes writing dependencies a lot clearer and straightforward for me.
