### ISSUE TITLE
[polyglot-yaml] Add ability to customise list element types

### ISSUE THREAD

**Issue by Tzrlk** [takari/polyglot-maven#152]
Following on from #151, there should be an annotation that allows for list items to be customised in special circumstances. Given the following configuration:
```yaml
configuration:
  pluginOptions:
    - option1
    - option2
```

The xml that gets generated ends up like this:
```xml
<configuration>
  <pluginOptions>
    <pluginOption>option1</pluginOption>
    <pluginOption>option2</pluginOption>
  </pluginOptions>
</configuration>
```

Unfortunately, in my specific case, the xml generated needs to be like this:
```xml
<configuration>
  <pluginOptions>
    <option>option1</option>
    <option>option2</option>
  <pluginOptions>
</configuration>
```

A potential solution is to add a tag option (http://yaml.org/spec/1.1/#id858961) which gets read and interpreted as the element type ([examples here][1]), e.g.:
```yaml
configuration:
  pluginOptions: !option
    - option1
    - option2
```

or add parameterisation to the tag and try to find the metadata during parsing:
```yaml
configuration:
  pluginOptions: !xml:element:option
    - option1
    - option2
```

If tags aren't usable, the parser could always look at lists and split the name on `:`. e.g.:
```yaml
configuration:
  pluginOptions:option:
    - option1
    - option2
```

Or tags could be used statically to specify an element with metadata:
```yaml
configuration:
  pluginOptions: !clist
    elementType: option
    elements:
      - option1
      - option2
```

[1]: https://bitbucket.org/asomov/snakeyaml/src/tip/src/test/java/org/yaml/snakeyaml/Example2_24Test.java?fileviewer=file-view-default
