### ISSUE TITLE
[YAML] [Structure] [Suggestion] Use lists rather than maps

### ISSUE THREAD

**Issue by JamesYeoman** [takari/polyglot-maven#175]
``` yaml
dependencies:
- {groupId: ch.qos.logback, artifactId: logback-classic, version: '${logback.version}'}
- {groupId: ch.qos.logback, artifactId: logback-core, version: '${logback.version}'}
```
just doesn't look quite right. What I had imagined it as is the following
```yaml
dependencies:
  - Logback-Classic:
    - groupId: ch.qos.logback
    - artifactId: logback-classic
    - version: ${logback.version}
  - Commons-Lang:
    - groupId: ch.qos.logback
    - artifactId: logback-core
    - version: ${logback.version}
```
Or possibly something like this
```yaml
dependencies:
  ch.qos.logback:
    logback-classic:
      - version: ${logback.version}
    logback-core:
      - version: ${logback.version}
```

**Comment by mosabua** [comment]
Not sure how that is logic to imply groupId and artifactId but no version.

**Comment by mosabua** [comment]
If anything I can image:

```
dependencies:
  - groupId: ch.qos.logback
    artifactId: logback-classic
    version: ${logback.version}
  - groupId: ch.qos.logback
    artifactId: logback-core
    version: ${logback.version}
```

**Comment by JamesYeoman** [comment]
> Not sure how that is logic to imply groupId and artifactId but no version.
> If anything I can image:
> 
> ```
> dependencies:
>   - groupId: ch.qos.logback
>     artifactId: logback-classic
>     version: ${logback.version}
>   - groupId: ch.qos.logback
>     artifactId: logback-core
>     version: ${logback.version}
> ```

The implying was kinda just me over-DRYing. Your suggestion is basically what I was shooting for. I just tried to group the artifacts by common groupIds

I will update the OP now

**Comment by jdimeo** [comment]
Aren't these the same thing and both supported by YAML syntax?

**Comment by dragetd** [comment]
```yaml
- {foo: bar, bleep: bloop}
- {foo2: bar, bleep2: bloop}
```

is equivalent to
```yaml
- foo: bar
  bleep: bloop
- foo2: bar
  bleep2: bloop
```

Both are a list of mappings. The curly braces are just a short-form for writing a map. The YAML parser should treat both the same.
