### ISSUE TITLE
TOML support

### ISSUE THREAD

**Issue by GameGlitz** [takari/polyglot-maven#228]
As a long term user of basically every configuration system I've seen, TOML is by far the most unapologetically modern method of writing anything possible, and should be ridiculously easy to parse.

I may contribute to make a plugin myself however I do see this would fit for basically every user as it would make not only sectioning the pom easier but reading it too.

```toml
modelVersion = "4.0.0"

groupId = "com.example"
artifactId = "HelloWorld"
version = "1.0.0"

name = "Hello World [Parent]"

[properties]
    java.version = "1.8"
    project.build.sourceEncoding = "UTF-8"

[repositories]
    [repositories.repository]
        id = "central"
        url = "https://repo1.maven.org/maven2"

[dependencies]
    [dependencies.dependency]
        groupId = "org.projectlombok"
        artifactId = "lombok"
        version = "LATEST"
    [dependencies.dependency]
        groupId = "com.google.code.gson"
        artifactId = "gson"
        version = "LATEST"
```
