### ISSUE TITLE
polyglot-yaml does not handle nested lists

### ISSUE THREAD

**Issue by dmos62** [takari/polyglot-maven#44]
GIven this `pom.yml`:

```

---
artifactId: raudondvaris
groupId: dmos
modelVersion: 4.0.0
packaging: war
prerequisites: {maven: 3.3.3}
version: 1.0
build:
  outputDirectory: ${project.build.directory}/${project.build.finalName}/WEB-INF/classes
  plugins:
    - artifactId: proguard-maven-plugin
      groupId: com.github.wvengen
      version: 2.0.11
      configuration:
        libs:
          - ${java.home}/lib/rt.jar
          - ${java.home}/lib/jsse.jar
```

`proguard-maven-plugin` throws following exception:

> Caused by: org.apache.maven.plugin.PluginConfigurationException: Unable to parse configuration of mojo com.github.wvengen:proguard-maven-plugin:2.0.11:proguard for parameter libs: Cannot assign configuration entry 'libs' with value '[/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar, /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jsse.jar]' of type java.lang.String to property of type java.util.List.

Running `mvn proguard:proguard -X` (`-X added`), reveals how the `<configuration>` tree is passed to proguard:

```
<configuration>
  ...
  <libs>[/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar, /usr/lib/jvm/java-7-o
penjdk-amd64/jre/lib/jsse.jar]</libs>
  ...
</configuration>
```

Apparently the `libs` list was collapsed into a one line version, but then was not translated to xml. Instead it was passed as a string, hence the exception.

`io.takari.polyglot/polyglot-yaml` is version `0.1.11`, which is the latest version.
### Way to reproduce:

Put above pom.yml sample into a `pom-test.yml`, and run: 

```
mvn io.takari.polyglot:polyglot-translate-plugin:translate -Dinput=pom-test.yml -Doutput=pom-test.xml
```

In the produced .xml `build.plugins.configuration.libs` is deformed.
