### ISSUE TITLE
[polyglot-yaml] does not handle shade plugin

### ISSUE THREAD

**Issue by pierods** [takari/polyglot-maven#62]
this valid xml shade configuration:

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.4.2</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>Xxxx</mainClass>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.DontIncludeResourceTransformer">
                                    <resource>
                                        .groovy
                                    </resource>
                                </transformer>
                            </transformers>
                            <artifactSet>
                                <excludes>
                                    <exclude>META-INF/*.groovy</exclude>
                                </excludes>
                            </artifactSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

is translated into:

  - artifactId: maven-shade-plugin
    executions:
    - configuration:
        transformers:
          transformer: {resource: .groovy}
        artifactSet:
          excludes: {exclude: META-INF/*.groovy}
      goals: [shade]
      id: default
      inherited: true
      phase: package
      priority: 0
    extensions: false
    groupId: org.apache.maven.plugins
    inherited: true
    version: 2.4.2

which fails to compile.

**Comment by vsipuli** [comment]
Also if you have multiple excludes/includes only the last one is preserved.

**Comment by Ribesg** [comment]
+1 on multiple include/exclude not working

**Comment by paulvi** [comment]
+1 @pierods yep, just tried

```yaml
  - groupId: org.apache.maven.plugins
    artifactId: maven-shade-plugin
    version: 2.4.2
    executions:
    - configuration:
        transformers:
          transformer: {resource: .groovy}
        artifactSet:
          excludes: {exclude: META-INF/*.groovy}
      goals: [shade]
      id: default
      inherited: true
      phase: package
      priority: 0
```

**Comment by paulvi** [comment]
as @rvowles  said in https://github.com/takari/polyglot-maven/issues/82#issuecomment-211829697

> you are hitting an issue with yaml itself there, it cannot handle more than one key named the same thing in the same "hash". Ansible suffers greatly from this.

**Comment by Ribesg** [comment]
`excludes` can only contain `exclude` items, right? You should be able to just put a YAML list of items without keys here, as the key is always `exclude` anyway.

**Comment by paulvi** [comment]
@Ribesg Gael, I am not able, only did a small change https://github.com/takari/polyglot-maven/pull/81

and how about you? Have you seen the code?

**Comment by Ribesg** [comment]
Hey, it would be nice if we could get something done about this. I don't really have the time to dig into the code myself though :(

**Comment by vasyas** [comment]
After digging Maven docs, found a working version:
```
build:
  plugins:
    - artifactId: maven-shade-plugin
      groupId: org.apache.maven.plugins
      version: 2.4.3
      executions:
        - phase: package
          goals: [shade]
          configuration:
            transformers:
              org.apache.maven.plugins.shade.resource.ManifestResourceTransformer:
                manifestEntries:
                  Main-Class: alfaorders.AlfaOrdersMain
```

**Comment by mkristian** [comment]
are saying the latest maven-shade-plugin is working with the yaml DSL ?

**Comment by vasyas** [comment]
mkristian, yes.

I've been able to run maven-shade-plugin using yaml dsl.

**Comment by mkristian** [comment]
after reading the issue from the very top, I am not sure though if the original problem is already solved or not - but thanx for reporting your progress @vasyas

**Comment by rvowles** [comment]
I think I'm still a little lost as to why anyone would use the shade plugin anymore? I mean you can use Spring Boot Loader (by itself, with no Spring) without the nightmare that is the Shade plugin. I built Bathe on exploding jars and the swapped to Spring Boot Loader.

**Comment by Ribesg** [comment]
@vasyas @mkristian no, the issue isn't resolved at all. We need to be able to provide more than one include/exclude

@rvowles this issue isn't about if people should use the maven shade plugin or not, it's about Maven Polyglot not supporting such overused plugin for YAML.

**Comment by rvowles** [comment]
@Ribesg and as such, i'm not sure why i'm even following this issue. So I will unsub!

**Comment by crazyfrozenpenguin** [comment]
@Ribesg is correct. I just tried this and I have to hack it in order to make it work:

```yml
    - groupId: org.apache.maven.plugins
      artifactId: maven-shade-plugin
      version: 2.3
      executions:
        - phase: package
          goals: [ shade ]
          configuration:
            outputFile: "${project.build.directory}/${project.artifactId}-${project.version}-fat.jar"
            transformers:
              org.apache.maven.plugins.shade.resource.ManifestResourceTransformer:
                manifestEntries: { Main-Class: "${main.class}\nMain-Verticle: ${main.verticle}" }
              org.apache.maven.plugins.shade.resource.AppendingTransformer:
                resource: META-INF/services/io.vertx.core.spi.VerticleFactory
```

The manifestEntries above should allow for multiple entries like:
```yml
manifestEntries: { Main-Class: "${main.class}", "Main-Verticle: ${main.verticle}" }
```

**Comment by bmsantos** [comment]
@Ribesg is correct. I just tried this and I have to hack it in order to make it work:

```yml
    - groupId: org.apache.maven.plugins
      artifactId: maven-shade-plugin
      version: 2.3
      executions:
        - phase: package
          goals: [ shade ]
          configuration:
            outputFile: "${project.build.directory}/${project.artifactId}-${project.version}-fat.jar"
            transformers:
              org.apache.maven.plugins.shade.resource.ManifestResourceTransformer:
                manifestEntries: { Main-Class: "${main.class}\nMain-Verticle: ${main.verticle}" }
              org.apache.maven.plugins.shade.resource.AppendingTransformer:
                resource: META-INF/services/io.vertx.core.spi.VerticleFactory
```

The manifestEntries above should allow for multiple entries like:
```yml
manifestEntries: { Main-Class: "${main.class}", Main-Verticle: "${main.verticle}" }
```

**Comment by Ribesg** [comment]
Can we have somebody working on this?
The problem is simple, right now you can only have one include and one exclude, as this does not work in YAML:
````yaml
  - artifactId: maven-shade-plugin
    groupId: org.apache.maven.plugins
    version: 2.4.3
    executions:
    - phase: package
      goals: [shade]
      configuration:
        artifactSet:
          includes:
            include: 'com.example.foo' # Erased by the following line
            include: 'org.example.bar'
````
It would be nice to be able to provide a list here:
````yaml
  - artifactId: maven-shade-plugin
    groupId: org.apache.maven.plugins
    version: 2.4.3
    executions:
    - phase: package
      goals: [shade]
      configuration:
        artifactSet:
          includes:
          - 'com.example.foo'
          - 'org.example.bar'
````
