### ISSUE TITLE
Tools support

### ISSUE THREAD

**Issue by paulvi** [takari/polyglot-maven#71]
@fbricon It may be easy to add some editors (e.g. for `atom`, `yaml`), but will m2e see this?
Can pom.xml files be generated for use with existing tools?

**Comment by fbricon** [comment]
m2e won't support native polyglot maven unless we do some non trivial changes there, starting with being able to load maven extensions per project. Someone needs to step up to make it happen.

Now https://github.com/jbosstools/m2e-polyglot-poc is a workaround, but not really a long term solution.

**Comment by paulvi** [comment]
- [Bug 465483 - Support polyglot maven](https://bugs.eclipse.org/bugs/show_bug.cgi?id=465483) in Eclipse

work in progress for http://www.nodeclipse.org/updates/polyglot-maven-ide-pack/

![groovy-pom-editor](https://cloud.githubusercontent.com/assets/1614482/14645203/50cda0da-0687-11e6-9438-a318cac54f16.PNG)


https://github.com/Nodeclipse/polyglot-maven-editors

**Comment by lefou** [comment]
IntelliJ has already (minimal) support for polyglot: https://confluence.jetbrains.com/display/IDEADEV/IntelliJ+IDEA+2016.3+163.4830.24+Release+Notes

For Eclipse, there is an somewhat experimental plugin which (re-)generates the `pom.xml`s from the polylgot pom's: https://github.com/jbosstools/m2e-polyglot-poc

**Comment by paulvi** [comment]
Thanks, Tobias. I am fully aware of current tooling support (as did my bits #72)

**Comment by mosabua** [comment]
I am closing the issue since this project wont implement tool support. The tool maintainer can do that if they want.

**Comment by ebousse** [comment]
Sorry to dig up this issue, just wanted to share the following workaround: you can ask polyglot to automatically generate a `pom.xml` for you each tome maven runs, thus making IDEs happy.

Sample from my `pom.yaml` file:

```yaml
build:
  plugins:

    # To automatically generate a pom.xml, to make IDEs happy
    - groupId: io.takari.polyglot
      artifactId: polyglot-translate-plugin
      version: 0.4.8
      executions:
        - goals: ['translate']
          id: 'yml2xml'
          phase: 'validate'
          configuration:
            input: pom.yml
            output: pom.xml
```
